### ISSUE TITLE
Make NuGet package compatible with NuGet 3.0

### ISSUE THREAD

**Issue by psfrolov** [csMACnz/coveritypublisher#10]
The package fails to install with NuGet 3.0 in VS 2015.

**Comment by csMACnz** [comment]
This is now fixed in 0.11.0.  For some reason, I can't see any of the 0.11.\* pre-releases or the release from the 2015 client using the v3 api. Adding the v2 api it shows up and installs correctly. I Assume given time it will show up in 2015 as well. Might be a local cache thing, since it shows up in the v3 api:
https://api.nuget.org/v3/registration1/publishcoverity/index.json

**Comment by csMACnz** [comment]
Just note that in 0.11.0 the exe is not in a **tools** folder inside the nuget package. This may affect some of your scripts.
